#!/bin/bash

declare -A STATIONS

STATIONS["bauhaus.fm"]="http://bauhaus.fm:8000/_a.m3u"
STATIONS["BBC Radio 3"]="http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p"
STATIONS["BBC Radio 4"]="http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p"
STATIONS["BBC Radio 4 Extra"]="http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4extra_mf_p"
STATIONS["BBC World Service"]="http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk"
STATIONS["Boom 97.3"]="https://newcap.leanstream.co/CHBMFM"
STATIONS["CBC Radio One (Toronto)"]="http://cbc_r1_tor.akacast.akamaistream.net/7/632/451661/v1/rc.akacast.akamaistream.net/cbc_r1_tor"
STATIONS["New Morning Radio"]="https://www.radioking.com/play/new-morning-radio"
STATIONS["Radio Aporee"]="http://radio.aporee.org:8000/aporee_high.m3u"
STATIONS["Resonance FM"]="http://54.77.136.103:8000/resonance"
STATIONS["Resonance Extra"]="http://54.77.136.103:8000/resonance-extra"
STATIONS["Soundart Radio"]="http://icecast.commedia.org.uk:8000/soundart.mp3"
STATIONS["STAPLR"]="http://staplr.org:8000/staplr.ogg"
STATIONS["TSF Jazz"]="https://tsfjazz.ice.infomaniak.ch:80/tsfjazz-high.mp3"
STATIONS["WFMU"]="http://wfmu.org/wfmu.pls"
STATIONS["WQXR"]="https://stream.wqxr.org/wqxr-web"
STATIONS["WQXR New Sounds"]="https://q2stream.wqxr.org/q2-web"
STATIONS["WWOZ"]="https://wwoz-sc.streamguys1.com/wwoz-hi.mp3"
STATIONS["Zoomer"]="http://65.19.131.139/mzmedia-cfzmamaac1-ibc2"

PLAYER="mpv --no-ytdl --quiet" # mpv without the YouTube hook script

# If a station is specified as an argument, play it, then exit.
if [ -n "$1" ]
then
    $PLAYER "${STATIONS[$1]}"
    exit
fi

# Otherwise, present a menu.

SELECTED=$(whiptail --title "Whip Radio" --menu "Choose a station" 20 60 12 \
		    "bauhaus.fm" "" \
		    "BBC Radio 3" "" \
		    "BBC Radio 4" "" \
		    "BBC Radio 4 Extra" "" \
		    "BBC World Service" "" \
		    "Boom 97.3" "" \
		    "CBC Radio One (Toronto)" "" \
		    "New Morning Radio" "" \
		    "Radio Aporee" "" \
		    "Resonance FM" "" \
		    "Resonance Extra" "" \
		    "Soundart Radio" "" \
		    "STAPLR" "" \
		    "TSF Jazz" "" \
		    "WFMU" "" \
		    "WQXR" "" \
		    "WQXR New Sounds" "" \
		    "WWOZ" "" \
		    "Zoomer" "" \
		    2>&1 >/dev/tty
	)

clear

if [ -z "$SELECTED" ]
then
    # Use Cancel to quit permanently
    echo "Quitting"
else
    echo -e "\033[1m ... $SELECTED ... \033[m"
    echo
    $PLAYER "${STATIONS[$SELECTED]}"
    # After quitting a station, rerun the script to choose another
    $0
fi


# echo ${STATIONS["BBC Radio Three"]}

# echo "Keys"
# echo "${!STATIONS[@]}"

# echo "--"
# for K in "${!STATIONS[@]}"; do echo -n "$K" ' '; done
# echo "--"

# LIST=""
# for K in "${!STATIONS[@]}"; do
#     LIST+="$K . "
# done
# echo $LIST

# echo "Loop"
# for K in "${!STATIONS[@]}"; do echo $K; done

# echo "Loop both"
# for K in "${!STATIONS[@]}"; do echo $K --- ${STATIONS[$K]}; done

# whiptail --title "Restore Files" --menu "Please " 14 40 6 "Test One" "Test" `for K in "${!STATIONS[@]}"; do echo -n "$K" "${STATIONS[$K]}"; done`
# whiptail --title "Restore Files" --menu "Please " 25 40 15 $LIST
